# version format
version: 2.6.{build}

environment:
  access_token:
    secure: eWAovbJD8C/F5ObWegnOimwNFyeU1vXzW6lwbJzhHpSUgjT+CMexMcPUBMKrm+Wl
  psgallery_key:
    secure: FuPgJskczZMptxRgdUlBAy7OYmXBQl4zq86kXXSmBt6wKudnM2PK7W6cM7bj0te1
  coveralls_key:
    secure: cWv4+OPfqRLSt7I4f+p3lEixKoYZzi42IDc7C4Kf+2WZW/dO+H+RBCM7m0Si2uuP

skip_commits:
  files:
    - .github\*
    - .vscode\*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
    - appveyor.yml
    - CHANGELOG.md
  message: /update readme.*|update version.*|update appveyor.*/

only_commits:
  files:
    - build\
    - psPAS\
    - Tests\

#os: WMF 5
image: Visual Studio 2017

install:
#  - ps: . .\build\install.ps1
- pwsh.exe -File .\build\install.ps1
build_script:
#  - ps: . .\build\build.ps1
- pwsh.exe -File .\build\build.ps1
test_script:
#  - ps: . .\build\test.ps1
- pwsh.exe -File .\build\test.ps1
deploy_script:
#  - ps: . .\build\deploy.ps1
- pwsh.exe -File .\build\deploy.ps1